Repository NooChuHan/Algorithm_CodeReview, pull requests merged in 2023-07, with the labels that each got.

#24 [week4] 양상우 정리
  week4/양상우/H-Index.js
  week4/양상우/K번째수.js
  week4/양상우/가장큰수.js
Labels: 🔥매운맛리뷰🔥, 🤖효율적인코드를원해요🤖

#19 Woongstar
  week3/양지웅/DiskController.java
  week3/양지웅/Main.java
  week3/양지웅/MoreSpicy.java
Labels: 💗순한맛리뷰💗

#20 [Week4] 김승덕 풀이
  week4/김승덕/H-Index.js
  week4/김승덕/K번째수.js
  week4/김승덕/가장 큰 수.js
Labels: 🔥매운맛리뷰🔥, 🤖효율적인코드를원해요🤖

#25 [week5] 양상우
  week5/양상우/모음사전.js
  week5/양상우/전력망을둘로나누기.js
  week5/양상우/피로도.js
Labels: 🔥매운맛리뷰🔥, 📢도움📢, 🤖효율적인코드를원해요🤖

#28 [week6] 양상우 풀이
  week6/양상우/구명보트.js
  week6/양상우/단속카메라.js
  week6/양상우/섬연결하기.js
Labels: 🔥매운맛리뷰🔥, 📢도움📢, 🤖효율적인코드를원해요🤖
